/* C Ching by Timothy Boettinger
 * I am a student currently studying C Programming
 * After learning of the srand() and rand() function
 * I was reminded of the ancient divination practice
 * where a person seeks answers or clarity within
 * through consulting a generated patten.
 * I hope to convey the same essence in my program as
 * demonstrated below.
 * Although one may argue that this essentially being
 * digital in nature, I hope the love of Programming
 * and thirst for wisdom may lead this to help others
 * as the patterns have helped me.
 * Enjoy, and may your path be blessed.
 * Disclaimer: portions of this code have been
 *    generated by Artificial Intelligence. The purpose
 *    is not to diminish the creativity of this endeavor,
 *    simply to continue practicing and being exposed to
 *    concepts of which I have yet to uncover in my studies.
 *
 *    This consultation also led to a more modular project
 *    something I was not familiar with until now.
 */

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/* Define the parameters of the program here
 * Although I have learned about constants
 * it did not originally occur that they may be
 * useful throughout this project
 */
#define NUM_LINES 6
#define NUM_COINS 3
#define USER_QUERY_BUFFER_SIZE 256
/* Original code called for these as their own functions,
 * and i was unaware of bool typing in regards to this project.
 * castSingleLine was lineCoins [3][2] with the intention of
 * 0, 1, 2 positions and 0 or 1 as heads or tails.
 */
int castSingleLine(void);
void printLine(int value, bool isSecondary);
bool hasChangingLines(const int lines[]);

int main() {
  srand(time(NULL));
  /* I had originally intended for the rand and srand
   * to be used within the arrays, however this was a portion
   * that was altered to allow for coin randomness effect
   */
  int lineValues[NUM_LINES];
  char userQuery[USER_QUERY_BUFFER_SIZE];

  printf("I am grateful that you decided to communicate with the seemingly "
         "invisible!\n");
  printf("Please enter your query...\n");
  fgets(userQuery, sizeof(userQuery), stdin);
  /* I was unfamiliar with fgets and originally opted for scanf
   * though AI pointed out that this is likely a much safer
   * option for buffer overflows
   */
  printf("\nThe answer to your query is being generated...\n");

  for (int i = 0; i < NUM_LINES; i++) {
    lineValues[i] = castSingleLine();
  }
  /* Print results */
  printf("\nPrimary Hexagram:\n\n");
  for (int i = NUM_LINES - 1; i >= 0; i--) {
    printf("Line %d: ", i + 1);
    printLine(lineValues[i], false);
  }

  if (hasChangingLines(lineValues)) {
    printf("\nSecondary Hexagram after apply changing lines:\n\n");
    for (int i = NUM_LINES - 1; i >= 0; i--) {
      printf("Line %d: ", i + 1);
      printLine(lineValues[i], true);
    }
  } else {
    printf("\nNo Changing lines.\n");
  }

  return 0;
}

int castSingleLine(void) {
  int sum = 0;
  for (int i = 0; i < NUM_COINS; i++) {
    int coinToss = rand() % 2;
    sum += (coinToss == 1) ? 3 : 2;
  }
  return sum;
}

void printLine(int value, bool isSecondary) {
  switch (value) {
  case 6:
    if (isSecondary) {
      printf("~~~~~   (Changed from Old Yin)\n");
    } else {
      printf("~~ ~~   (Old Yin, changing)\n");
    }
    break;
  case 7: // Young Yang
    printf("~~~~~   (Young Yang)\n");
    break;
  case 8: // Young Yin
    printf("~~ ~~   (Young Yin)\n");
    break;
  case 9: // Old Yang
    if (isSecondary) {
      printf("~~ ~~   (Changed from Old Yang)\n");
    } else {
      printf("~~~~~   (Old Yang, changing)\n");
    }
    break;
  }
}

bool hasChangingLines(const int lines[]) {
  for (int i = 0; i < NUM_LINES; i++) {
    if (lines[i] == 6 || lines[i] == 9) {
      return true;
    }
  }
  return false;
}
